import { Router } from 'express';
import userRouter from './users';
import eventRouter from './events';
import orderRouter from './orders';
import optionsRouter from './options';
import checkinRouter from './checkins';
import summarysRouter from './summarys';
import paidLeaveRouter from './paidleaves';
import departmentRouter from './departments';
import informationRouter from './informations';
import notificationRouter from './notifications';
import taxDependentRouter from './taxDependents';
import { authJwt, requireRoles } from '../../middlewares';
const adminRouter: Router = Router();

adminRouter.use(authJwt);
adminRouter.use(requireRoles(['ADMIN']));
adminRouter.use('/users', userRouter);
adminRouter.use('/events', eventRouter);
adminRouter.use('/orders', orderRouter);
adminRouter.use('/options', optionsRouter);
adminRouter.use('/checkins', checkinRouter);
adminRouter.use('/summarys', summarysRouter);
adminRouter.use('/paidleaves', paidLeaveRouter);
adminRouter.use('/departments', departmentRouter);
adminRouter.use('/informations', informationRouter);
adminRouter.use('/notifications', notificationRouter);
adminRouter.use('/tax-dependents', taxDependentRouter);
export default adminRouter;
