import { GET_ENUM_FOR_ADMIN_CONTROLLER } from './options';
import {
    CREATE_USER_FOR_ADMIN_CONTROLLER,
    CREATE_ORDER_FOR_ADMIN_CONTROLLER,
    ADMIN_CREATE_DEPARTMENT_CONTROLLER,
    CREATE_EVENTS_FOR_ADMIN_CONTROLLER,
    DELETE_EVENTS_FOR_ADMIN_CONTROLLER,
    ADMIN_DELETE_INFORMATION_CONTROLLER,
    UPDATE_STATUS_TAX_DEPENDENT_CONTROLLER,
    CREATE_INFORMATION_FOR_ADMIN_CONTROLLER,
    GET_INFORMATIONS_BY_ADMIN_ID_CONTROLLER,
    CREATE_NOTIFICATION_FOR_ADMIN_CONTROLLER,
    UPDATE_APPROVE_OVERTIME_REQUEST_BY_ADMIN_CONTROLLER,
} from './dashboards/admin';
import {
    UPDATE_INVENTORY_FOR_LEADER_CONTROLLER,
    CREATE_OVERTIME_REQUEST_BY_LEADER_CONTROLLER,
    DESTROY_OVERTIME_REQUEST_BY_LEADER_CONTROLLER,
} from './dashboards/leaderAndOther';
export {
    GET_ENUM_FOR_ADMIN_CONTROLLER,
    CREATE_USER_FOR_ADMIN_CONTROLLER,
    CREATE_ORDER_FOR_ADMIN_CONTROLLER,
    ADMIN_CREATE_DEPARTMENT_CONTROLLER,
    CREATE_EVENTS_FOR_ADMIN_CONTROLLER,
    DELETE_EVENTS_FOR_ADMIN_CONTROLLER,
    ADMIN_DELETE_INFORMATION_CONTROLLER,
    UPDATE_INVENTORY_FOR_LEADER_CONTROLLER,
    UPDATE_STATUS_TAX_DEPENDENT_CONTROLLER,
    CREATE_INFORMATION_FOR_ADMIN_CONTROLLER,
    GET_INFORMATIONS_BY_ADMIN_ID_CONTROLLER,
    CREATE_NOTIFICATION_FOR_ADMIN_CONTROLLER,
    CREATE_OVERTIME_REQUEST_BY_LEADER_CONTROLLER,
    DESTROY_OVERTIME_REQUEST_BY_LEADER_CONTROLLER,
    UPDATE_APPROVE_OVERTIME_REQUEST_BY_ADMIN_CONTROLLER,
};
