CREATE TABLE payrolls
(
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL REFERENCES users(id),
    date VARCHAR(10) NOT NULL,
    pay_date VARCHAR(10) NOT NULL,
    work_time FLOAT NULL,
    over_time FLOAT NULL,
    paid_vacation_days FLOAT NULL,
    weekend_time FLOAT NULL,
    paid_vacation_pay FLOAT NULL,
    work_salary FLOAT NULL,
    shift_night_salary FLOAT NULL,
    over_time_salary FLOAT NULL,
    refund_money FLOAT NULL,
    other_pay FLOAT NULL,
    weekend_salary FLOAT NULL,
    attendance_allowance_pay FLOAT NULL,
    travel_allowance_pay FLOAT NULL,
    bonus_pay FLOAT NULL,
    gross_salary FLOAT NOT NULL,
    income_tax FLOAT NULL,
    social_insurance FLOAT NULL,
    health_insurance FLOAT NULL,
    uniform_deduction FLOAT NULL,
    accident_insurance FLOAT NULL,
    club_fee FLOAT NULL,
    rent_home FLOAT NULL,
    cost_of_living FLOAT NULL,
    other_deduction FLOAT NULL,
    net_salary FLOAT NOT NULL,
    created_at DATE NULL ,
    updated_at DATE NULL,
    deleted_at DATE NULL,
    UNIQUE(user_id, pay_date, date)
);