CREATE TABLE payrolls
(
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL REFERENCES users(id),
    date VARCHAR(10) NOT NULL,
    pay_date VARCHAR(10) NOT NULL,
    work_time FLOAT NULL DEFAULT 0,
    over_time FLOAT NULL DEFAULT 0,
    paid_vacation_days FLOAT NULL DEFAULT 0,
    weekend_time FLOAT NULL DEFAULT 0,
    paid_vacation_pay FLOAT NULL DEFAULT 0,
    work_salary FLOAT NULL DEFAULT 0,
    shift_night_salary FLOAT NULL DEFAULT 0,
    over_time_salary FLOAT NULL DEFAULT 0,
    refund_money FLOAT NULL DEFAULT 0,
    other_pay FLOAT NULL DEFAULT 0,
    weekend_salary FLOAT NULL DEFAULT 0,
    attendance_allowance_pay FLOAT NULL DEFAULT 0,
    travel_allowance_pay FLOAT NULL DEFAULT 0,
    bonus_pay FLOAT NULL DEFAULT 0,
    gross_salary FLOAT NOT NULL,
    income_tax FLOAT NULL DEFAULT 0,
    social_insurance FLOAT NULL DEFAULT 0,
    health_insurance FLOAT NULL DEFAULT 0,
    uniform_deduction FLOAT NULL DEFAULT 0,
    accident_insurance FLOAT NULL DEFAULT 0,
    club_fee FLOAT NULL DEFAULT 0,
    rent_home FLOAT NULL DEFAULT 0,
    cost_of_living FLOAT NULL DEFAULT 0,
    other_deduction FLOAT NULL DEFAULT 0,
    shift_night FLOAT NULL DEFAULT 0,
    net_salary FLOAT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at DATE NULL ,
    updated_at DATE NULL,
    deleted_at DATE NULL,
    UNIQUE
    (user_id, pay_date, date)
);

-- ALTER TABLE payrolls ADD COLUMN shift_night FLOAT NULL DEFAULT 0;