import { Router } from 'express';
import getInforOfUserRouter from './infomationRouterModule/getInformationOfuser.router';
import getInformationByIdRouter from './infomationRouterModule/getInformationById.router';
import searchAllRouter from './infomationRouterModule/getInformationByField.router';
import deleteInformation from './infomationRouterModule/deleteInformationById.router';
const informationRouter: Router = Router();
informationRouter.use('/getinforofuser', getInforOfUserRouter);
informationRouter.use('/getinforbyid', getInformationByIdRouter);
informationRouter.use('/getallinforbyfield', searchAllRouter);
informationRouter.use('/deleteinformationbyid', deleteInformation);
export default informationRouter;
